CREATE TABLE LOCAL ( 
    cod_loc NUMBER(4) PRIMARY KEY, 
    nome VARCHAR2(25) NOT NULL );

CREATE TABLE DEPTO ( 
    cod_depto NUMBER(4) PRIMARY KEY, 
    nome VARCHAR2(25) NOT NULL, 
    cod_loc NUMBER(4), 
    FOREIGN KEY (cod_loc) REFERENCES LOCAL(cod_loc) );

CREATE TABLE CARGO ( 
    cod_cargo NUMBER(4) PRIMARY KEY, 
    descricao VARCHAR2(30) NOT NULL, 
    CBO NUMBER(6) );

CREATE TABLE FUNC ( 
    cod_func NUMBER(4) PRIMARY KEY, 
    sobrenome VARCHAR2(25) NOT NULL, 
    nome VARCHAR2(25) NOT NULL, 
    salario NUMBER(10,2), 
    dt_adm DATE, 
    cod_depto NUMBER(4), 
    cod_cargo NUMBER(4), 
    FOREIGN KEY (cod_depto) REFERENCES DEPTO(cod_depto),
    FOREIGN KEY (cod_cargo) REFERENCES CARGO(cod_cargo)
);

DESC LOCAL;
DESC DEPTO;
DESC CARGO;
DESC FUNC;

INSERT INTO LOCAL VALUES (1, 'São Paulo');
INSERT INTO LOCAL VALUES (2, 'Belo Horizonte');
INSERT INTO LOCAL VALUES (3, 'Guarulhos');
INSERT INTO LOCAL VALUES (4, 'Campinas');
INSERT INTO LOCAL VALUES (5, 'Curitiba');
INSERT INTO LOCAL VALUES (6, 'Rio de Janeiro');

UPDATE depto
SET nome_depto = ‘RH’
WHERE cod_depto = 44;


DROP TABLE DEPTO;

DELETE
FROM DEPTO
WHERE COD_DEPTO = 44;


DROP TABLE DEPTO CASCADE;
DROP TABLE CARGO CASCADE;
DROP TABLE FUNCIONARIO CASCADE;
DROP TABLE LOCAL CASCADE

UPDATE FUNCIONARIO
SET SALARIO = 2200
WHERE COD_FUN = 23
UPDATE Depto
SET cod_loc = 7
WHERE cod_depto = 33

SELECT * FROM DEPTO;
SELECT * FROM FUNCIONARIO